- "git-" => "git " rename
git-dash is being deprecated.

diff --git a/.tip/bin/tip-automerge-all b/.tip/bin/tip-automerge-all
--- a/.tip/bin/tip-automerge-all
+++ b/.tip/bin/tip-automerge-all
@@ -19,22 +19,22 @@ BRANCHES=$(cat $BFILE | grep -v ^#)
 
 echo "integrating the following branches: $BRANCHES"
 
-git-checkout -b $BRANCH master || { exit -1; }
+git checkout -b $BRANCH master || { exit -1; }
 
 for N in $BRANCHES; do
   echo $N
-  git-merge $N || {
+  git merge $N || {
     echo merge conflict - run tip-mergetool
     echo
     echo running subshell - type "exit" when resolved
-    bash || { echo "merge aborted manually!"; git-checkout master; exit -1; }
+    bash || { echo "merge aborted manually!"; git checkout master; exit -1; }
 
-    git-add $(git-ls-files -u | cut -f2 | sort | uniq)
-    git-commit -m "Manual merge." || exit -1;
+    git add $(git ls-files -u | cut -f2 | sort | uniq)
+    git commit -m "Manual merge." || exit -1;
   }
 done
 
-git-checkout master
+git checkout master
 
 echo "created integration branch $BRANCH successfully!"
 
